### ISSUE TITLE
Run script with sudo permission

### ISSUE THREAD

**Issue by ajitsahu** [nrayapati/ssh-deploy-library#4]
@nrayapati ,
Sorry to bother you again
seems there is an issue with the script while running with sudo permission.
https://github.com/nrayapati/ssh-deploy-library/blob/c9f3059f90e50a3c62ba3a25e482458bfc6be975/vars/sshDeploy.groovy#L176
for command with sudo is working well but it's giving error for script.
```
case "scripts":
            sshScript remote: remote, script: command, sudo: isSudo
```
even I tried with `def isSudo = true`

Please have a look
Thanks in advance

**Comment by nrayapati** [comment]
It is not supported by plugin. https://github.com/jenkinsci/ssh-steps-plugin/blob/master/README.adoc#sshscript

**Comment by ajitsahu** [comment]
I see, in original doc also it's not mentioned.
https://gradle-ssh-plugin.github.io/docs/#_execute_a_script
curious to know is there any other way where we can make it possible from below link
https://github.com/jenkinsci/ssh-steps-plugin/blob/84dbd0c90d37afa979f0f23c9396e99d1447f3b1/src/main/groovy/org/jenkinsci/plugins/sshsteps/SSHService.groovy#L193

**Comment by nrayapati** [comment]
Unfortunately we can't add sudo support for script as it is being streamed as a file. But you can achieve the same by sending (put) the script on to the box and use execute it as a sudo command.

**Comment by ajitsahu** [comment]
I got it, I think this is the only way.
Thank you so much
