### ISSUE TITLE
copy file globs using puts

### ISSUE THREAD

**Issue by corporate-gadfly** [nrayapati/ssh-deploy-library#5]
Not really a bug report, but more of a question.

Is there a possibility of "putting" multiple files in the `from` section?

Here's a scenario in a pipeline:
- `copyArtifacts` is used to copy a war file from some upstream build (not part of this pipeline)
- Filename is unknown _(the pattern is know, e.g., `rest-*.war`)_
- how do I tell `puts` to use the pattern?

**Comment by corporate-gadfly** [comment]
I ended up using `sshPublisher`.

**Comment by nrayapati** [comment]
Just in case, `sshPut` and `sshGet` does support retrieving files from a folder by pattern using following params. 

* `filterBy`
* `filterRegex`

https://github.com/jenkinsci/ssh-steps-plugin#sshput
https://github.com/jenkinsci/ssh-steps-plugin#sshget
